
BLENDER="F:\steam game\steamapps\common\Blender\blender.exe"
DIST=../dist

all : \
    $(DIST)/ocean.pnct \
    $(DIST)/ocean.scene \

$(DIST)/ocean.scene : ocean.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "ocean.blend:Main" "$(DIST)/ocean.scene"

$(DIST)/ocean.pnct : ocean.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "ocean.blend:Main" "$(DIST)/ocean.pnct" 